[build]
  publish = "build/web"
  command = "flutter build web --release --web-renderer html"

[build.environment]
  FLUTTER_VERSION = "3.16.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200