name: timetable_management
description: Timetable Management System
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^19.5.0
  permission_handler: ^11.0.1
  timezone: ^0.10.1
  path: ^1.8.3
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/vignan logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/